<a href="https://colab.research.google.com/github/stanbuklovskyi/algorithms-from-scratch/blob/main/kmeans_clustering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#This is an example of from scratch implementation of KNN clustering algorithm



## First, let's generate some random data to work with

In [2]:
# import necessary libraries
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
from scipy.spatial.distance import cdist

In [3]:
# let's choose a random seed and generate some data
np.random.seed(444)
n = 50 # number of points
# 50 points of 3D data
X = np.random.random((n,3))
# print(X)

In [4]:
# 3d scatter plot of the data
fig = px.scatter_3d(x=X[:,0], y=X[:,1], z=X[:,2])
fig.show()

## Algorithm:
1.   Initialize centers
2.   While not converged: , 
*   Update cluster membership
*   Update centers











In [5]:
# initialize centers (random pick of centers)
k = 4 # number of clusters we want to initialze
centers = X[np.random.choice(n, k, replace=False)]
centers

array([[0.91667412, 0.46727482, 0.84964217],
       [0.39847232, 0.25190614, 0.67305517],
       [0.94483394, 0.51914402, 0.01375533],
       [0.47489478, 0.95956803, 0.7848371 ]])

In [6]:
# now let's calculate distance from each point to the "center"
# I'll use Euclidean distance for this case
# (o-la,la. Fancy broadcasting for distance finding, although doesn't work fast for big chunks of data) 
(((X.reshape(n,1,3) - centers.reshape(1,k,3))**2).sum(axis=2))**0.5

array([[0.41753665, 0.72078992, 0.70524566, 0.41508843],
       [0.92743419, 0.69743102, 0.55692672, 1.1837972 ],
       [0.92897712, 0.49891482, 0.72120173, 0.89590538],
       [0.81469033, 0.65267315, 1.1638896 , 0.30440551],
       [0.72474387, 0.52236846, 0.7973085 , 0.38667496],
       [0.74875947, 0.35387653, 0.69690062, 0.93627392],
       [0.8080095 , 0.92591175, 0.25059676, 0.84534527],
       [0.53744011, 0.49142813, 0.70820135, 0.34193946],
       [0.66462116, 0.72050049, 1.00468066, 0.        ],
       [0.56204588, 0.79373093, 0.80616024, 0.30008108],
       [0.8075473 , 0.67779694, 0.36776446, 1.05113921],
       [0.88531715, 0.44194997, 1.31485614, 0.81736795],
       [1.0485105 , 0.70255797, 0.90658985, 0.69530016],
       [0.        , 0.58830242, 0.8379679 , 0.66462116],
       [0.50447613, 0.81416885, 0.83038632, 0.35576765],
       [0.59501979, 0.41520603, 0.55826246, 0.58517483],
       [1.03333444, 0.59239787, 1.00106802, 0.73289338],
       [0.70668773, 0.50633196,

In [7]:
# general distance solution
# get memory for distances object
distances = np.zeros((n,k))

for i in range(k):
    distances[:,i] = ((X - centers[i])**2).sum(axis=1)**0.5

# distances

In [8]:
# using cdist is preferable if there is not need for...
#... specific distance metrics
distances = cdist(X, centers)

# closest points for each cluster
closest = np.argmin(distances, axis=1)
closest

array([3, 2, 1, 3, 3, 1, 2, 3, 3, 3, 2, 1, 3, 0, 3, 1, 1, 1, 1, 1, 1, 1,
       3, 2, 3, 3, 3, 3, 1, 1, 1, 1, 2, 3, 2, 2, 1, 1, 3, 0, 2, 0, 3, 2,
       1, 1, 0, 3, 1, 1])

In [12]:
# center of a prticular cluster
X[closest == 0].mean(axis=0)

array([0.88305792, 0.51837735, 0.75511456])

In [13]:
# reassign centers to centers of each cluster
for i in range(k):
    centers[i,:] = X[closest == 0].mean(axis=0)

## All code pieces together

In [20]:
np.random.seed(666666666)
centers = X[np.random.choice(n, k, replace=False)]
closest = np.zeros(n).astype(int)

# convergence loop
while True:
    old_closest = closest.copy()
    print(closest)
    distances = cdist(X, centers)
    closest = np.argmin(distances, axis=1)

    for i in range(k):
        centers[i,:] = X[closest == i].mean(axis=0)
    # repeat until no change
    if all(closest == old_closest):
        break

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0]
[2 1 1 2 2 1 3 2 2 2 1 0 2 2 2 2 2 1 0 0 0 2 2 3 2 2 2 2 0 0 0 2 3 2 3 1 0
 0 2 0 3 2 3 2 0 0 1 2 0 0]
[2 1 1 2 2 1 3 2 2 2 1 0 2 2 2 2 2 1 0 0 0 0 2 3 2 2 2 2 0 0 0 1 3 2 3 1 0
 0 2 0 3 2 3 2 0 0 1 2 0 0]
[2 1 1 2 2 1 3 2 2 2 1 0 2 2 2 2 0 1 0 0 0 0 2 3 2 2 2 2 0 0 0 1 3 2 3 1 0
 0 2 0 3 2 3 2 0 0 1 2 0 0]


In [22]:
# visualize results
# 3d scatter plot of the data
fig = px.scatter_3d(x=X[:,0], y=X[:,1], z=X[:,2], color=closest)
fig.show()

## Last part is wrapping up this whole alorithm into a function

In [23]:
def kmeans(X, k):
    n = X.shape[0]
    centers = X[np.random.choice(n, k, replace=False)]
    closest = np.zeros(n).astype(int)

    # convergence loop
    while True:
        old_closest = closest.copy()
        distances = cdist(X, centers)
        closest = np.argmin(distances, axis=1)

        for i in range(k):
            centers[i,:] = X[closest == i].mean(axis=0)
        # repeat until no change
        if all(closest == old_closest):
            break
    return closest, centers

In [24]:
# check if the function work
labels, centers = kmeans(X, 4)
print(labels)
print(centers)

[3 1 0 2 0 1 1 3 3 3 1 2 0 3 3 0 0 1 2 0 2 2 3 1 0 0 3 2 2 2 2 0 1 2 1 1 2
 2 3 2 1 3 0 0 2 2 1 0 2 2]
[[0.25781934 0.63121043 0.33566059]
 [0.83209967 0.34371559 0.20514331]
 [0.33475271 0.38402302 0.75047119]
 [0.71696653 0.82192095 0.73117719]]
